### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by morganzero** [maxime1907/docker-filegator#1]
Hi mate, thanks for this docker image. I've been searching for a dockerized version for a while and found yours today. finally.
However, I get `Folder not writable: /repository/` when trying to access the app.
![image](https://user-images.githubusercontent.com/57449785/141779848-edaa1035-690a-49f0-a958-8d4cc83f3307.png)

Any ideas?

Thanks again!

**Comment by maxime1907** [comment]
Hey there!

Thanks for reporting this issue, I fixed it in [1ca6b66e3cdce53dd41c0c13d93c268f5fc7b684](https://github.com/maxime1907/docker-filegator/commit/1ca6b66e3cdce53dd41c0c13d93c268f5fc7b684)
You can now pull the latest version, it should work as intended.

**Comment by morganzero** [comment]
Thanks alot, i can confirm i see the login form now. However, what is the default password and username ?

And are there variables I can add to my docker-compose to set new details? e.g: `PASSWORD=` `USERNAME=`

**Comment by maxime1907** [comment]
Username: admin
Password: admin123

For more informations, take a look at the [https://docs.filegator.io/accounts.html](filegator documentation) accounts

**Comment by morganzero** [comment]
Sorry, I meant, if I can set my own variables directly in my docker-compose ?

**Comment by maxime1907** [comment]
You can't right now, but just login with the default credentials and set up your own username/password directly in the web interface

**Comment by maxime1907** [comment]
Ah my bad you can actually mount /var/www/localhost/filegator/private/users.json and change/add credentials as you wish
